services:
  web:
    build: ./app
    env_file:
      - .env
    ports:
      - 80:${PORT}
    expose:
      - ${PORT}
    volumes:
      - web-django:/usr/src/app
    command: >
      gunicorn
        app.asgi:application
        -k uvicorn.workers.UvicornWorker
        -b :${PORT}
        --timeout 60

volumes:
  web-django:
